### ISSUE TITLE
相比 coredump 有什么优缺点？

### ISSUE THREAD

**Issue by wangjiewen** [dongzhiyan-stack/user_stack_backstrace-in-kernel#1]
如果 user 崩溃会有 coredump 可以来参考解决，为什么需要将用户态崩溃的栈信息打印到内核态？coredump 内容更完整，这个只有堆栈信息，项目上真的有实用么？

**Comment by dongzhiyan-stack** [comment]
详细内容可以看下我CLK演讲的ppt。举个简单的例子，研发环境用gdb+coredump解决偶然出现的段错误、double free问题确实很方便，信息还多。但是在非研发环境，比如在某所学校一台运行linux系统的机器异常了，现场很难远程控制，研发或者技术支持不太可能再去现场敲命令运行coredump复现问题。而内核对应用栈回溯，并把日志保存到存储设备，技术支持找到日志拍个照给研发，研发就知道哪里出问题。

**Comment by wangjiewen** [comment]
好奇问一下，这个是个人项目还是公司已用的？

**Comment by dongzhiyan-stack** [comment]
是个人项目，源码是我在家近几个月开发完善的。但是arm64内核对段错误应用栈回溯并打印pc值，我在2017开发并在公司项目使用至今，没有问题，这个功能十几行代码就用实现。
